/** Словарь русских тематических слов → английский (диалог, выбор темы, mixed-input fallback). */
export const RU_TOPIC_KEYWORD_TO_EN: Record<string, string> = {
  солнце: 'sun',
  солнечный: 'sun',
  погода: 'weather',
  дождь: 'rain',
  снег: 'snow',
  море: 'sea',
  океан: 'ocean',
  река: 'river',
  озеро: 'lake',
  пляж: 'beach',
  гора: 'mountain',
  горы: 'mountains',
  лес: 'forest',
  природа: 'nature',
  спорт: 'sports',
  футбол: 'football',
  теннис: 'tennis',
  баскетбол: 'basketball',
  хоккей: 'hockey',
  плавание: 'swimming',
  бег: 'running',
  велосипед: 'bicycle',
  музыка: 'music',
  песня: 'song',
  песни: 'songs',
  гитара: 'guitar',
  пианино: 'piano',
  фильм: 'movie',
  фильмы: 'movies',
  кино: 'cinema',
  мультик: 'cartoon',
  мультики: 'cartoons',
  книга: 'book',
  книги: 'books',
  школа: 'school',
  урок: 'lesson',
  уроки: 'lessons',
  учёба: 'studies',
  работа: 'work',
  еда: 'food',
  готовка: 'cooking',
  хлеб: 'bread',
  яйцо: 'egg',
  яйца: 'eggs',
  кот: 'cat',
  кошка: 'cat',
  кошки: 'cats',
  собака: 'dog',
  собаки: 'dogs',
  животные: 'animals',
  семья: 'family',
  друзья: 'friends',
  друг: 'friend',
  путешествие: 'travel',
  путешествия: 'travel',
  город: 'city',
  страна: 'country',
  дом: 'home',
  машина: 'car',
  компьютер: 'computer',
  телефон: 'phone',
  игра: 'game',
  игры: 'games',
  лето: 'summer',
  зима: 'winter',
  весна: 'spring',
  осень: 'autumn',
  космос: 'space',
  динозавры: 'dinosaurs',
  робот: 'robot',
  роботы: 'robots',
}

export function normalizeTopicToken(token: string): string {
  return token.toLowerCase().replace(/^[^a-zа-яё]+|[^a-zа-яё]+$/gi, '')
}
