import type { QuickTestVariant } from '@/lib/quickTest/types'

export const introducingYourselfVariants: QuickTestVariant[] = [
  {
    id: 'variant-1',
    questions: [
      {
        id: 'iy-v1-q1',
        prompt: 'I ___ from Spain.',
        options: ['am', 'is', 'are'],
        correctIndex: 0,
        explanationRu: 'С I всегда am: I am from…',
        slot: 1,
        format: 'complete',
        skillTag: 'be-am',
        mistakeTag: 'be-agreement',
      },
      {
        id: 'iy-v1-q2',
        prompt: 'Выбери естественную фразу.',
        options: ["I'm a student.", 'I is a student.', 'I are a student.'],
        correctIndex: 0,
        explanationRu: 'I am / I’m + роль или профессия.',
        slot: 2,
        format: 'natural',
        skillTag: 'be-am',
        mistakeTag: 'be-agreement',
      },
      {
        id: 'iy-v1-q3',
        prompt: 'Ошибка: «I is from Russia.»',
        options: ['is → am', 'нужно are', 'убрать from'],
        correctIndex: 0,
        explanationRu: 'I am from…, не I is.',
        slot: 3,
        format: 'find-error',
        skillTag: 'be-am',
        mistakeTag: 'be-agreement',
      },
      {
        id: 'iy-v1-q4',
        prompt: 'Как сказать «Меня зовут Anna»?',
        options: ["I'm Anna.", 'I Anna.', 'I be Anna.'],
        correctIndex: 0,
        explanationRu: 'I’m + имя — короткое представление.',
        slot: 4,
        format: 'context',
        skillTag: 'intro-name',
        mistakeTag: 'missing-be',
      },
      {
        id: 'iy-v1-q5',
        prompt: 'Что верно?',
        options: ["I'm from Italy.", 'I from Italy.', 'I is from Italy.'],
        correctIndex: 0,
        explanationRu: 'Нужна форма be: I’m from…',
        slot: 5,
        format: 'distinguish',
        skillTag: 'be-am',
        mistakeTag: 'missing-be',
      },
    ],
  },
]
