import type { QuickTestVariant } from '@/lib/quickTest/types'

export const itsTimeToVariants: QuickTestVariant[] = [
  {
    id: 'variant-1',
    questions: [
      {
        id: 'itt-v1-q1',
        prompt: "It's time ___ go.",
        options: ['to', 'for', 'at'],
        correctIndex: 0,
        explanationRu: 'It’s time to + глагол: It’s time to go.',
        slot: 1,
        format: 'complete',
        skillTag: 'its-time-to',
        mistakeTag: 'time-to-prep',
      },
      {
        id: 'itt-v1-q2',
        prompt: 'Выбери естественную фразу.',
        options: ["It's time to sleep.", "It's time sleep.", "It's time for sleep go."],
        correctIndex: 0,
        explanationRu: 'После time — to + глагол.',
        slot: 2,
        format: 'natural',
        skillTag: 'its-time-to',
        mistakeTag: 'missing-to',
      },
      {
        id: 'itt-v1-q3',
        prompt: "Ошибка: «It's time go home.»",
        options: ['нужно to go', 'нужно going', 'убрать time'],
        correctIndex: 0,
        explanationRu: 'It’s time to go home.',
        slot: 3,
        format: 'find-error',
        skillTag: 'its-time-to',
        mistakeTag: 'missing-to',
      },
      {
        id: 'itt-v1-q4',
        prompt: 'Пора начинать. Как сказать?',
        options: ["It's time to start.", "It's time start.", "It's the time start."],
        correctIndex: 0,
        explanationRu: 'It’s time to start.',
        slot: 4,
        format: 'context',
        skillTag: 'its-time-to',
        mistakeTag: 'missing-to',
      },
      {
        id: 'itt-v1-q5',
        prompt: 'Что верно?',
        options: ["It's time to eat.", "It's time eating.", "It's time eat."],
        correctIndex: 0,
        explanationRu: 'to + базовая форма глагола, не -ing и не голый глагол.',
        slot: 5,
        format: 'distinguish',
        skillTag: 'its-time-to',
        mistakeTag: 'time-ing',
      },
    ],
  },
]
