import type { QuickTestVariant } from '@/lib/quickTest/types'

export const whoLikesVariants: QuickTestVariant[] = [
  {
    id: 'variant-1',
    questions: [
      {
        id: 'wl-v1-q1',
        prompt: 'Who ___ pizza?',
        options: ['likes', 'like', 'does like'],
        correctIndex: 0,
        explanationRu: 'После Who в роли подлежащего глагол в 3-м лице: Who likes…?',
        slot: 1,
        format: 'complete',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v1-q2',
        prompt: 'Выбери естественный вопрос.',
        options: ['Who likes tea?', 'Who does like tea?', 'Who like tea?'],
        correctIndex: 0,
        explanationRu: 'Who = подлежащее → likes, без does.',
        slot: 2,
        format: 'natural',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v1-q3',
        prompt: 'Где ошибка: «Who does play football?»',
        options: ['лишнее does', 'нужно plays', 'нужно Who is'],
        correctIndex: 0,
        explanationRu: 'Когда Who — кто делает действие, does не ставим.',
        slot: 3,
        format: 'find-error',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v1-q4',
        prompt: 'Друг спрашивает, кто любит кофе. Что сказать?',
        options: ['Who likes coffee?', 'Who do likes coffee?', 'Who liking coffee?'],
        correctIndex: 0,
        explanationRu: 'Короткий вопрос с Who + likes.',
        slot: 4,
        format: 'context',
        skillTag: 'who-subject',
        mistakeTag: 'who-agreement',
      },
      {
        id: 'wl-v1-q5',
        prompt: 'Что верно?',
        options: ['Who likes apples?', 'Who like apples?', 'Who does likes apples?'],
        correctIndex: 0,
        explanationRu: 'Who + likes; like и does likes — типичные ошибки.',
        slot: 5,
        format: 'distinguish',
        skillTag: 'who-subject',
        mistakeTag: 'who-agreement',
      },
    ],
  },
  {
    id: 'variant-2',
    questions: [
      {
        id: 'wl-v2-q1',
        prompt: 'Who ___ English?',
        options: ['speaks', 'speak', 'does speak'],
        correctIndex: 0,
        explanationRu: 'Who как подлежащее → speaks.',
        slot: 1,
        format: 'complete',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v2-q2',
        prompt: 'Выбери правильный вопрос.',
        options: ['Who lives here?', 'Who does live here?', 'Who live here?'],
        correctIndex: 0,
        explanationRu: 'Who lives — без does.',
        slot: 2,
        format: 'natural',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v2-q3',
        prompt: 'Ошибка в «Who do wants ice cream?»',
        options: ['do → убрать; wants ок', 'нужно want', 'нужно Who is'],
        correctIndex: 0,
        explanationRu: 'Убираем do: Who wants…?',
        slot: 3,
        format: 'find-error',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v2-q4',
        prompt: 'Кто играет в теннис? На английском:',
        options: ['Who plays tennis?', 'Who play tennis?', 'Who does plays tennis?'],
        correctIndex: 0,
        explanationRu: 'Who + plays.',
        slot: 4,
        format: 'context',
        skillTag: 'who-subject',
        mistakeTag: 'who-agreement',
      },
      {
        id: 'wl-v2-q5',
        prompt: 'Какой вариант без ошибки?',
        options: ['Who works on Sundays?', 'Who work on Sundays?', 'Who does works on Sundays?'],
        correctIndex: 0,
        explanationRu: 'Who works — одна форма 3-го лица.',
        slot: 5,
        format: 'distinguish',
        skillTag: 'who-subject',
        mistakeTag: 'who-agreement',
      },
    ],
  },
  {
    id: 'variant-3',
    questions: [
      {
        id: 'wl-v3-q1',
        prompt: 'Who ___ chocolate?',
        options: ['loves', 'love', 'does love'],
        correctIndex: 0,
        explanationRu: 'Who loves…? — подлежащее Who.',
        slot: 1,
        format: 'complete',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v3-q2',
        prompt: 'Естественная фраза:',
        options: ['Who knows the answer?', 'Who does know the answer?', 'Who know the answer?'],
        correctIndex: 0,
        explanationRu: 'Who knows — без does.',
        slot: 2,
        format: 'natural',
        skillTag: 'who-subject',
        mistakeTag: 'who-extra-does',
      },
      {
        id: 'wl-v3-q3',
        prompt: 'Что не так: «Who does goes first?»',
        options: ['does + goes вместе нельзя', 'нужно go', 'нужно Who are'],
        correctIndex: 0,
        explanationRu: 'Либо Who goes, либо (редко) Who does go — но не does goes.',
        slot: 3,
        format: 'find-error',
        skillTag: 'who-subject',
        mistakeTag: 'who-double-mark',
      },
      {
        id: 'wl-v3-q4',
        prompt: 'Спросить, кто смотрит этот фильм:',
        options: ['Who watches this film?', 'Who watch this film?', 'Who does watches this film?'],
        correctIndex: 0,
        explanationRu: 'Who + watches.',
        slot: 4,
        format: 'context',
        skillTag: 'who-subject',
        mistakeTag: 'who-agreement',
      },
      {
        id: 'wl-v3-q5',
        prompt: 'Выбери верное.',
        options: ['Who teaches maths?', 'Who teach maths?', 'Who does teaches maths?'],
        correctIndex: 0,
        explanationRu: 'Who teaches — одна «метка» 3-го лица.',
        slot: 5,
        format: 'distinguish',
        skillTag: 'who-subject',
        mistakeTag: 'who-double-mark',
      },
    ],
  },
]
