import type { TopicGoalPack } from '@/types/adaptiveRetention'

export const TOPIC_GOAL_PACKS: TopicGoalPack[] = [
  {
    id: 'food-basics',
    title: 'Food Basics',
    goal: 'Заказать еду, понять меню и сказать, что нравится.',
    audience: ['child', 'teen', 'adult'],
    minLevel: 'a1',
    estimatedMinutes: 7,
    worldIds: ['home', 'travel'],
    tags: ['food', 'restaurant', 'taste', 'order', 'pay'],
    phraseTemplates: ['I would like ...', 'Can I have ...?', 'It tastes ...'],
    practiceModes: ['flashcard', 'quick-choice', 'cloze-context', 'say-it'],
    successCriteria: 'Пользователь уверенно узнаёт базовые слова еды и может собрать 2-3 фразы заказа.',
  },
  {
    id: 'airport-survival',
    title: 'Airport Survival',
    goal: 'Пройти аэропорт: багаж, регистрация, посадка, задержка.',
    audience: ['teen', 'adult'],
    minLevel: 'a1',
    estimatedMinutes: 10,
    worldIds: ['travel', 'core'],
    tags: ['airport', 'passport', 'luggage', 'gate', 'boarding'],
    phraseTemplates: ['Where is gate ...?', 'I have one bag.', 'My flight is delayed.'],
    practiceModes: ['knowledge-check', 'listen-and-pick', 'sentence-builder', 'use-it'],
    successCriteria: 'Пользователь понимает ключевые airport-слова и может произнести 3 survival-фразы.',
  },
  {
    id: 'hotel-check-in',
    title: 'Hotel Check-in',
    goal: 'Заселиться в отель, попросить помощь и решить простую проблему.',
    audience: ['teen', 'adult'],
    minLevel: 'a1',
    estimatedMinutes: 8,
    worldIds: ['travel', 'home'],
    tags: ['hotel', 'reservation', 'room', 'key', 'problem'],
    phraseTemplates: ['I have a reservation.', 'Can I have the key?', 'There is a problem with ...'],
    practiceModes: ['quick-choice', 'cloze-context', 'use-it'],
    successCriteria: 'Пользователь узнаёт отельные слова и строит базовые просьбы.',
  },
  {
    id: 'travel-basics',
    title: 'Travel Basics',
    goal: 'Спросить дорогу, купить билет и понять транспорт.',
    audience: ['child', 'teen', 'adult'],
    minLevel: 'a1',
    estimatedMinutes: 8,
    worldIds: ['travel', 'core'],
    tags: ['travel', 'ticket', 'bus', 'train', 'map', 'weather'],
    phraseTemplates: ['How do I get to ...?', 'I need a ticket.', 'Is it far?'],
    practiceModes: ['flashcard', 'reverse-choice', 'listen-and-pick'],
    successCriteria: 'Пользователь понимает базовые travel-слова и выбирает нужную фразу по ситуации.',
  },
  {
    id: 'daily-small-talk',
    title: 'Daily Small Talk',
    goal: 'Поддержать короткий разговор о себе, семье и планах.',
    audience: ['child', 'teen', 'adult'],
    minLevel: 'a1',
    estimatedMinutes: 6,
    worldIds: ['home', 'school', 'core'],
    tags: ['hello', 'family', 'plans', 'question', 'answer'],
    phraseTemplates: ['How are you?', 'I live in ...', 'Today I want to ...'],
    practiceModes: ['say-it', 'sentence-builder', 'use-it'],
    successCriteria: 'Пользователь отвечает на 3 простых вопроса без долгой паузы.',
  },
  {
    id: 'work-starter',
    title: 'Work Starter',
    goal: 'Понять базовые рабочие слова: встреча, задача, письмо, дедлайн.',
    audience: ['adult'],
    minLevel: 'a2',
    estimatedMinutes: 10,
    worldIds: ['school', 'digital', 'core'],
    tags: ['work', 'meeting', 'task', 'email', 'deadline'],
    phraseTemplates: ['I will send an email.', 'The deadline is ...', 'Let us discuss the task.'],
    practiceModes: ['cloze-context', 'sentence-builder', 'use-it'],
    successCriteria: 'Пользователь применяет рабочие слова в коротких фразах.',
  },
  {
    id: 'digital-life',
    title: 'Digital Life',
    goal: 'Понимать слова про телефон, приложения, сообщения и поиск.',
    audience: ['teen', 'adult'],
    minLevel: 'a1',
    estimatedMinutes: 7,
    worldIds: ['digital', 'core'],
    tags: ['phone', 'app', 'message', 'password', 'search'],
    phraseTemplates: ['Open the app.', 'Send me a message.', 'I forgot my password.'],
    practiceModes: ['speed-review', 'quick-choice', 'use-it'],
    successCriteria: 'Пользователь уверенно узнаёт digital-слова и применяет их в бытовом контексте.',
  },
]

export function getTopicGoalPack(packId: string): TopicGoalPack | null {
  return TOPIC_GOAL_PACKS.find((pack) => pack.id === packId) ?? null
}
