/**
 * Human discovery copy for syllabus topicKeys.
 * Keys without an entry get a fallback humanizer in seed builder.
 */
export type SyllabusTopicMeta = {
  titleRu: string
  titleEn: string
  teaser: string
  aliases?: string[]
  /** Preferred CEFR level when key appears on multiple FAQ levels. */
  level?: 'A1' | 'A2' | 'B1' | 'B2'
}

export const SYLLABUS_TOPIC_META: Record<string, SyllabusTopicMeta> = {
  to_be: {
    titleRu: 'Глагол to be (am / is / are)',
    titleEn: 'to be',
    teaser: 'Кто я, какой я, где я — через am / is / are.',
    aliases: ['am', 'is', 'are', 'i am', 'i am busy'],
    level: 'A1',
  },
  present_simple: {
    titleRu: 'Настоящее простое',
    titleEn: 'Present Simple',
    teaser: 'Привычки и факты: I work, she works.',
    aliases: ['present simple', 'she works', 'every day'],
    level: 'A1',
  },
  present_continuous: {
    titleRu: 'Настоящее длительное',
    titleEn: 'Present Continuous',
    teaser: 'Что происходит сейчас: I am working.',
    aliases: ['present continuous', 'i am working', 'now'],
    level: 'A1',
  },
  articles: {
    titleRu: 'Артикли a / an / the',
    titleEn: 'Articles',
    teaser: 'Когда нужен a, an или the.',
    aliases: ['a an the', 'article'],
    level: 'A1',
  },
  there_is: {
    titleRu: 'There is / there are',
    titleEn: 'There is / are',
    teaser: 'Как сказать, что что-то есть или нет.',
    aliases: ['there is', 'there are'],
    level: 'A1',
  },
  have_got: {
    titleRu: 'Have / have got',
    titleEn: 'have / have got',
    teaser: 'Что у меня есть: I have / I’ve got.',
    aliases: ['have', 'have got', 'i have', "i've got", 'has'],
    level: 'A1',
  },
  pronouns: {
    titleRu: 'Местоимения',
    titleEn: 'Pronouns',
    teaser: 'I / me / my / mine и другие.',
    level: 'A1',
  },
  plurals: {
    titleRu: 'Множественное число',
    titleEn: 'Plurals',
    teaser: 'book → books, child → children.',
    level: 'A1',
  },
  adjectives: {
    titleRu: 'Прилагательные',
    titleEn: 'Adjectives',
    teaser: 'Описание: big, happy, interesting.',
    level: 'A1',
  },
  modals: {
    titleRu: 'Модальные глаголы',
    titleEn: 'Modals',
    teaser: 'can / must / should — умение, правило, совет.',
    aliases: ['can', 'must', 'should', 'may', 'might'],
    level: 'A1',
  },
  imperative: {
    titleRu: 'Повелительное наклонение',
    titleEn: 'Imperative',
    teaser: 'Просьбы и команды: Open the door.',
    level: 'A1',
  },
  time_numbers: {
    titleRu: 'Время и числа',
    titleEn: 'Time & numbers',
    teaser: 'Часы, даты, числа в речи.',
    level: 'A1',
  },
  adverbs_time: {
    titleRu: 'Наречия времени',
    titleEn: 'Time adverbs',
    teaser: 'always, usually, sometimes, never.',
    level: 'A1',
  },
  предлоги: {
    titleRu: 'Предлоги',
    titleEn: 'Prepositions',
    teaser: 'in / on / at и другие короткие слова места и времени.',
    aliases: ['prepositions', 'in on at'],
    level: 'A1',
  },
  вопросы_и_порядок_слов: {
    titleRu: 'Вопросы и порядок слов',
    titleEn: 'Questions & word order',
    teaser: 'Who / What / Where и порядок в вопросе.',
    aliases: ['who', 'who likes', 'questions', 'wh-'],
    level: 'A1',
  },
  отрицания_и_краткие_ответы: {
    titleRu: 'Отрицания и краткие ответы',
    titleEn: 'Negation & short answers',
    teaser: 'don’t / doesn’t и Yes, I do / No, I don’t.',
    level: 'A1',
  },
  базовые_союзы_и_связь_идеи: {
    titleRu: 'Союзы and / but / because',
    titleEn: 'Basic connectors',
    teaser: 'Связать две мысли просто.',
    level: 'A1',
  },
  указательные_и_количественные_слова: {
    titleRu: 'This / that / some / any',
    titleEn: 'Demonstratives & quantifiers',
    teaser: 'Этот / тот и сколько.',
    level: 'A1',
  },
  past_simple: {
    titleRu: 'Прошедшее простое',
    titleEn: 'Past Simple',
    teaser: 'Что было: I went, she liked.',
    aliases: ['past simple', 'yesterday', 'ago'],
    level: 'A2',
  },
  past_continuous: {
    titleRu: 'Прошедшее длительное',
    titleEn: 'Past Continuous',
    teaser: 'Что происходило: I was reading.',
    level: 'A2',
  },
  present_perfect: {
    titleRu: 'Present Perfect',
    titleEn: 'Present Perfect',
    teaser: 'Опыт и результат: I have been to…',
    aliases: ['present perfect', 'have been', 'ever never'],
    level: 'A2',
  },
  future: {
    titleRu: 'Будущее (will / going to)',
    titleEn: 'Future',
    teaser: 'Планы и решения: will / going to.',
    aliases: ['will', 'going to', 'future'],
    level: 'A2',
  },
  word_order: {
    titleRu: 'Порядок слов',
    titleEn: 'Word order',
    teaser: 'Прямой порядок и встроенные куски.',
    aliases: ['word order', 'i know what'],
    level: 'A2',
  },
  reported_speech: {
    titleRu: 'Косвенная речь / встроенный вопрос',
    titleEn: 'Reported / embedded',
    teaser: 'I know what she likes — без does внутри.',
    aliases: ['reported speech', 'embedded', 'she asked where'],
    level: 'A2',
  },
  comparatives: {
    titleRu: 'Степени сравнения',
    titleEn: 'Comparatives',
    teaser: 'bigger / more interesting / the best.',
    level: 'A2',
  },
  quantifiers: {
    titleRu: 'Much / many / a lot of',
    titleEn: 'Quantifiers',
    teaser: 'Сколько: much, many, a few, a little.',
    level: 'A2',
  },
  conditionals: {
    titleRu: 'Условные предложения',
    titleEn: 'Conditionals',
    teaser: 'If… — условие и результат.',
    aliases: ['if', 'conditional', 'zero first'],
    level: 'A2',
  },
  relative_clauses: {
    titleRu: 'Относительные придаточные',
    titleEn: 'Relative clauses',
    teaser: 'who / which / that в одной фразе.',
    level: 'A2',
  },
  gerunds_infinitives: {
    titleRu: 'Gerund / infinitive',
    titleEn: 'Gerunds & infinitives',
    teaser: 'like doing vs want to do.',
    level: 'A2',
  },
  phrasal_verbs: {
    titleRu: 'Фразовые глаголы',
    titleEn: 'Phrasal verbs',
    teaser: 'look for, give up, turn on.',
    level: 'A2',
  },
  prepositions: {
    titleRu: 'Предлоги (A2+)',
    titleEn: 'Prepositions',
    teaser: 'Зависимые предлоги: interested in, good at.',
    level: 'A2',
  },
  connectors: {
    titleRu: 'Связки текста',
    titleEn: 'Connectors',
    teaser: 'however, although, so…',
    level: 'A2',
  },
  indefinites: {
    titleRu: 'Somebody / anything / nowhere',
    titleEn: 'Indefinites',
    teaser: 'Неопределённые местоимения.',
    level: 'A2',
  },
  too_enough: {
    titleRu: 'Too / enough',
    titleEn: 'too / enough',
    teaser: 'Слишком и достаточно.',
    level: 'A2',
  },
  used_to: {
    titleRu: 'Used to',
    titleEn: 'used to',
    teaser: 'Раньше обычно: I used to…',
    level: 'A2',
  },
  agreement: {
    titleRu: 'Согласование',
    titleEn: 'Agreement',
    teaser: 'Подлежащее и глагол согласуются.',
    level: 'A2',
  },
  passive_causative: {
    titleRu: 'Пассив и causative',
    titleEn: 'Passive / causative',
    teaser: 'was made / have something done.',
    level: 'A2',
  },
  past_perfect: {
    titleRu: 'Past Perfect',
    titleEn: 'Past Perfect',
    teaser: 'Что случилось раньше: had done.',
    level: 'B1',
  },
  present_perfect_continuous: {
    titleRu: 'Present Perfect Continuous',
    titleEn: 'Present Perfect Continuous',
    teaser: 'have been doing — длительность до сейчас.',
    level: 'B1',
  },
  so_such: {
    titleRu: 'So / such',
    titleEn: 'so / such',
    teaser: 'so tired / such a nice day.',
    level: 'B1',
  },
  time_reason_clauses: {
    titleRu: 'Придаточные времени и причины',
    titleEn: 'Time & reason clauses',
    teaser: 'when / while / because / since.',
    level: 'B1',
  },
  collocations: {
    titleRu: 'Коллокации',
    titleEn: 'Collocations',
    teaser: 'Слова, которые «дружат»: make a decision.',
    level: 'B2',
  },
  verb_patterns: {
    titleRu: 'Глагольные конструкции',
    titleEn: 'Verb patterns',
    teaser: 'suggest doing / refuse to…',
    level: 'B2',
  },
  // CEFR gaps (not FAQ mega-keys)
  its_time_to: {
    titleRu: 'It’s / It’s time to',
    titleEn: "It's time to / for",
    teaser: 'Обстановка и «пора»: It’s cold / It’s time to go.',
    aliases: ["it's time", 'its time', 'time to', 'time for', "it's cold"],
    level: 'A2',
  },
  be_going_to: {
    titleRu: 'be going to',
    titleEn: 'be going to',
    teaser: 'План или очевидное будущее: I’m going to…',
    aliases: ['going to', "i'm going to"],
    level: 'A2',
  },
  can_ability: {
    titleRu: 'Can — умение и просьба',
    titleEn: 'can (ability)',
    teaser: 'Умею / можно: I can swim. Can you help?',
    aliases: ['can you', 'i can'],
    level: 'A1',
  },
  wh_subject_questions: {
    titleRu: 'Вопрос к подлежащему (Who…?)',
    titleEn: 'Subject questions',
    teaser: 'Who saw you? — без did, когда Who = кто делает.',
    aliases: ['who saw', 'subject question', 'who likes'],
    level: 'A2',
  },
  would_like: {
    titleRu: 'Would like',
    titleEn: 'would like',
    teaser: 'Вежливое хочу: I’d like a coffee.',
    aliases: ["i'd like", 'would like'],
    level: 'A1',
  },
  possessive_s: {
    titleRu: 'Притяжательный ’s',
    titleEn: "Possessive 's",
    teaser: 'Чей: Anna’s book.',
    aliases: ["anna's", "possessive 's", 'whose'],
    level: 'A1',
  },
  object_pronouns: {
    titleRu: 'Объектные местоимения',
    titleEn: 'Object pronouns',
    teaser: 'После глагола — me / him / her, не I / he.',
    aliases: ['me him her', 'object pronoun'],
    level: 'A1',
  },
  frequency_adverbs: {
    titleRu: 'How often / частота',
    titleEn: 'Frequency',
    teaser: 'always → never: как часто.',
    aliases: ['how often', 'always usually'],
    level: 'A1',
  },
  countable_uncountable: {
    titleRu: 'Исчисляемые и неисчисляемые',
    titleEn: 'Countable / uncountable',
    teaser: 'a apple? rice / water без a.',
    aliases: ['countable', 'uncountable', 'much many'],
    level: 'A2',
  },
  zero_conditional: {
    titleRu: 'Zero conditional',
    titleEn: 'Zero conditional',
    teaser: 'If you heat ice, it melts — факты.',
    aliases: ['zero conditional', 'if you heat'],
    level: 'A2',
  },
  first_conditional: {
    titleRu: 'First conditional',
    titleEn: 'First conditional',
    teaser: 'If it rains, I’ll stay — реальное будущее.',
    aliases: ['first conditional', 'if it rains'],
    level: 'A2',
  },
  second_conditional: {
    titleRu: 'Second conditional',
    titleEn: 'Second conditional',
    teaser: 'If I were you… — гипотеза.',
    aliases: ['second conditional', 'if i were'],
    level: 'B1',
  },
  present_perfect_experience: {
    titleRu: 'Present Perfect — опыт',
    titleEn: 'Present Perfect (experience)',
    teaser: 'Have you ever…? — опыт в жизни.',
    aliases: ['have you ever', 'ever never'],
    level: 'A2',
  },
  should_advice: {
    titleRu: 'Should — совет',
    titleEn: 'should (advice)',
    teaser: 'You should… — мягкий совет.',
    aliases: ['you should', 'should'],
    level: 'A2',
  },
  must_have_to: {
    titleRu: 'Must / have to',
    titleEn: 'must / have to',
    teaser: 'Обязанность и запрет.',
    aliases: ['must', 'have to', "mustn't"],
    level: 'A2',
  },
  past_simple_irregular: {
    titleRu: 'Past Simple — неправильные',
    titleEn: 'Irregular past',
    teaser: 'go → went, see → saw.',
    aliases: ['went', 'irregular verbs', 'saw'],
    level: 'A2',
  },
  questions_do_does: {
    titleRu: 'Вопросы с do / does',
    titleEn: 'Do / Does questions',
    teaser: 'Do you…? Does she…?',
    aliases: ['do you', 'does she'],
    level: 'A1',
  },
  like_ing: {
    titleRu: 'Like + -ing',
    titleEn: 'like + -ing',
    teaser: 'I like reading — хобби через -ing.',
    aliases: ['like reading', 'like doing'],
    level: 'A1',
  },
  weather_it: {
    titleRu: 'Погода с It’s',
    titleEn: "Weather It's",
    teaser: 'It’s sunny / cold / raining.',
    aliases: ["it's sunny", "it's raining", 'weather'],
    level: 'A1',
  },
  telling_time: {
    titleRu: 'Который час',
    titleEn: 'Telling the time',
    teaser: 'What time is it? It’s half past…',
    aliases: ['what time', "o'clock", 'half past'],
    level: 'A1',
  },
  days_months: {
    titleRu: 'Дни и месяцы',
    titleEn: 'Days & months',
    teaser: 'on Monday, in July.',
    aliases: ['monday', 'july', 'days months'],
    level: 'A1',
  },
  comparative_as_as: {
    titleRu: 'As … as',
    titleEn: 'as … as',
    teaser: 'as tall as — сравнение равенства.',
    aliases: ['as tall as', 'as as'],
    level: 'A2',
  },
  present_perfect_just_already: {
    titleRu: 'Just / already / yet',
    titleEn: 'just / already / yet',
    teaser: 'Только что / уже / ещё не.',
    aliases: ['just already yet', 'have you … yet'],
    level: 'A2',
  },
  past_vs_present_perfect: {
    titleRu: 'Past Simple vs Present Perfect',
    titleEn: 'Past vs Present Perfect',
    teaser: 'yesterday vs ever / already.',
    aliases: ['past vs perfect', 'yesterday vs ever'],
    level: 'B1',
  },
  passive_basic: {
    titleRu: 'Пассив (базовый)',
    titleEn: 'Basic passive',
    teaser: 'English is spoken here.',
    aliases: ['is spoken', 'was made', 'passive'],
    level: 'B1',
  },
  reported_statements: {
    titleRu: 'Косвенная речь — утверждения',
    titleEn: 'Reported statements',
    teaser: 'He said (that) he was tired.',
    aliases: ['he said that', 'reported statements'],
    level: 'B1',
  },
}
