import type { LessonData } from '@/types/lesson'

export const whoLikesLesson: LessonData = {
  id: '2',
  topic: 'Who ...?',
  level: 'A2',
  repeatConfig: {
    ruleSummary: 'Строим вопросы с Who в Present Simple и отвечаем полными фразами с третьим лицом.',
    grammarFocus: ['Who questions', 'Present Simple', 'third person singular'],
    sourceSituations: ['Кто любит музыку?', 'Кто пьет чай?', 'Кто любит спорт?', 'Кто любит читать вечером?'],
    bannedTerms: ['past simple', 'present continuous', 'future', 'conditionals', 'passive'],
    qualityGate: {
      minScore: 0.6,
      maxSoftIssues: 4,
      rejectOnHardFailures: true,
    },
    stepBlueprints: [
      {
        stepNumber: 1,
        stepType: 'hook',
        learningGoal: 'Показать базовый вопрос Who likes ...? в бытовой ситуации.',
        exerciseType: 'fill_choice',
        answerFormat: 'choice',
        answerPolicy: 'strict',
        sourceCorrectAnswer: 'Anna likes music.',
        sourcePattern: 'Who likes + noun?',
        semanticAnchors: ['who', 'likes', 'music'],
        semanticExpectations: {
          pedagogicalRole: 'introduce_context',
          mustInclude: ['who', 'likes', 'music'],
          shouldInclude: ['anna'],
          mustAvoid: ['it is time to', 'past simple'],
          hintShouldMention: ['likes'],
          requireCyrillicHint: true,
          maxAcceptedAnswers: 1,
        },
      },
      {
        stepNumber: 2,
        stepType: 'theory',
        learningGoal: 'Пояснить, что после Who в таком вопросе глагол часто идёт в форме likes/reads/drinks.',
        exerciseType: 'fill_choice',
        answerFormat: 'choice',
        answerPolicy: 'strict',
        sourceCorrectAnswer: 'likes',
        sourcePattern: 'Who + verb-s',
        semanticAnchors: ['who', 'likes'],
        semanticExpectations: {
          pedagogicalRole: 'explain_rule',
          mustInclude: ['who', 'likes'],
          shouldInclude: ['-s', 'глагол'],
          mustAvoid: ['it is time to', 'future'],
          hintShouldMention: ['likes'],
          requireCyrillicHint: true,
          maxAcceptedAnswers: 1,
        },
      },
      {
        stepNumber: 3,
        stepType: 'practice_fill',
        learningGoal: 'Закрепить вопросительное слово Who в коротком паттерне.',
        exerciseType: 'translate',
        answerFormat: 'single_word',
        answerPolicy: 'strict',
        sourceCorrectAnswer: 'Who',
        sourcePattern: 'Who likes + noun?',
        semanticAnchors: ['who', 'likes'],
        semanticExpectations: {
          pedagogicalRole: 'controlled_pattern_drill',
          mustInclude: ['who', 'likes'],
          shouldInclude: ['tea'],
          mustAvoid: ['it is time to', 'present continuous'],
          hintShouldMention: ['кто'],
          requireCyrillicHint: true,
          maxAcceptedAnswers: 1,
        },
      },
      {
        stepNumber: 4,
        stepType: 'practice_fill',
        learningGoal: 'Собрать полный вопрос Who likes ...? на английском.',
        exerciseType: 'translate',
        answerFormat: 'full_sentence',
        answerPolicy: 'strict',
        sourceCorrectAnswer: 'Who likes music?',
        sourcePattern: 'Who likes + noun?',
        semanticAnchors: ['who', 'likes', 'music'],
        semanticExpectations: {
          pedagogicalRole: 'controlled_pattern_drill',
          mustInclude: ['who', 'likes', 'music'],
          shouldInclude: ['?'],
          mustAvoid: ['it is time to', 'past simple'],
          hintShouldMention: ['who', 'likes'],
          requireCyrillicHint: true,
          requireQuestionMarkInAnswer: true,
          maxAcceptedAnswers: 1,
        },
      },
      {
        stepNumber: 5,
        stepType: 'practice_apply',
        learningGoal: 'Дать вопрос и ответ в коротком бытовом мини-диалоге.',
        exerciseType: 'translate',
        answerFormat: 'full_sentence',
        answerPolicy: 'equivalent_variants',
        sourceCorrectAnswer: 'Who likes tea? My brother likes tea.',
        sourcePattern: 'Who likes + noun? Subject likes + noun.',
        semanticAnchors: ['who', 'likes', 'tea'],
        semanticExpectations: {
          pedagogicalRole: 'apply_in_new_situation',
          mustInclude: ['who', 'likes', 'tea'],
          shouldInclude: ['brother'],
          mustAvoid: ['it is time to', 'future'],
          hintShouldMention: ['вопрос', 'ответ'],
          requireCyrillicHint: true,
          requireQuestionMarkInAnswer: true,
          maxAcceptedAnswers: 3,
        },
      },
      {
        stepNumber: 6,
        stepType: 'feedback',
        learningGoal: 'Проверить различие между Who likes ...? и ошибочными формами без окончания -s.',
        exerciseType: 'fill_choice',
        answerFormat: 'choice',
        answerPolicy: 'strict',
        sourceCorrectAnswer: 'Who likes music?',
        sourcePattern: 'Who likes + noun?',
        semanticAnchors: ['who', 'likes', 'music'],
        semanticExpectations: {
          pedagogicalRole: 'contrast_check',
          mustInclude: ['who', 'likes', 'music'],
          shouldInclude: ['like'],
          mustAvoid: ['it is time to', 'past simple'],
          hintShouldMention: ['likes'],
          requireCyrillicHint: true,
          requireQuestionMarkInAnswer: true,
          maxAcceptedAnswers: 1,
        },
      },
    ],
  },
  steps: [
    {
      stepNumber: 1,
      stepType: 'hook',
      bubbles: [
        {
          type: 'positive',
          content: 'Сегодня потренируем короткие вопросы с Who и ответы о том, кто что любит.',
        },
        {
          type: 'info',
          content: 'Такие вопросы помогают быстро узнать, кто любит музыку, чай, спорт или другие вещи.',
        },
        {
          type: 'task',
          content: 'Выберите правильный ответ на вопрос: "Who likes music?"',
        },
      ],
      exercise: {
        type: 'fill_choice',
        question: 'Какой ответ подходит?',
        options: ['Anna likes music.', 'Who like music?', 'Anna like music.'],
        correctAnswer: 'Anna likes music.',
        acceptedAnswers: ['Anna likes music.'],
        answerFormat: 'choice',
        answerPolicy: 'strict',
        hint: 'В ответе с Anna нужен глагол likes.',
      },
      footerDynamic: 'Hook: Who likes ...?',
    },
    {
      stepNumber: 2,
      stepType: 'theory',
      bubbles: [
        {
          type: 'positive',
          content: 'Посмотрим на форму глагола после Who.',
        },
        {
          type: 'info',
          content: 'В вопросах вроде "Who likes music?" мы часто используем форму с -s: likes, drinks, reads.',
        },
        {
          type: 'task',
          content: 'Выберите правильное слово: "Who ___ music?"',
        },
      ],
      exercise: {
        type: 'fill_choice',
        question: 'Какой вариант грамматически верный?',
        options: ['like', 'likes', 'liking'],
        correctAnswer: 'likes',
        acceptedAnswers: ['likes'],
        answerFormat: 'choice',
        answerPolicy: 'strict',
        hint: 'В таком вопросе нужна форма likes.',
      },
      footerDynamic: 'Theory: Who + likes',
    },
    {
      stepNumber: 3,
      stepType: 'practice_fill',
      bubbles: [
        {
          type: 'positive',
          content: 'Теперь закрепим вопросительное слово.',
        },
        {
          type: 'info',
          content: 'Если вы спрашиваете "кто?", в начале будет Who.',
        },
        {
          type: 'task',
          content: 'Дополните вопрос одним словом: "___ likes tea?"',
        },
      ],
      exercise: {
        type: 'translate',
        question: 'Напишите одно слово.',
        correctAnswer: 'Who',
        acceptedAnswers: ['Who'],
        answerFormat: 'single_word',
        answerPolicy: 'strict',
        hint: 'Нужно вопросительное слово "кто".',
      },
      footerDynamic: 'Practice: Who',
    },
    {
      stepNumber: 4,
      stepType: 'practice_fill',
      bubbles: [
        {
          type: 'positive',
          content: 'Соберём целый вопрос.',
        },
        {
          type: 'info',
          content: 'Шаблон простой: Who + likes + noun?',
        },
        {
          type: 'task',
          content: 'Переведите на английский: "Кто любит музыку?"',
        },
      ],
      exercise: {
        type: 'translate',
        question: 'Напишите полный вопрос.',
        correctAnswer: 'Who likes music?',
        acceptedAnswers: ['Who likes music?'],
        answerFormat: 'full_sentence',
        answerPolicy: 'strict',
        hint: 'Начните с Who и используйте likes.',
      },
      footerDynamic: 'Practice: full question',
    },
    {
      stepNumber: 5,
      stepType: 'practice_apply',
      bubbles: [
        {
          type: 'positive',
          content: 'Теперь используем вопрос и ответ вместе.',
        },
        {
          type: 'info',
          content: 'После вопроса можно дать короткий ясный ответ с подлежащим.',
        },
        {
          type: 'task',
          content: 'Переведите на английский: "Кто любит чай? Мой брат любит чай."',
        },
      ],
      exercise: {
        type: 'translate',
        question: 'Напишите две короткие фразы.',
        correctAnswer: 'Who likes tea? My brother likes tea.',
        acceptedAnswers: ['Who likes tea? My brother likes tea.'],
        answerFormat: 'full_sentence',
        answerPolicy: 'equivalent_variants',
        hint: 'Сначала вопрос с Who, потом ответ с likes.',
      },
      footerDynamic: 'Practice: question and answer',
    },
    {
      stepNumber: 6,
      stepType: 'feedback',
      bubbles: [
        {
          type: 'positive',
          content: 'Финальная проверка: найдите правильную форму.',
        },
        {
          type: 'info',
          content: 'Помните: в этом шаблоне нам нужна форма likes, а не like.',
        },
        {
          type: 'task',
          content: 'Выберите правильный вопрос.',
        },
      ],
      exercise: {
        type: 'fill_choice',
        question: 'Какой вариант правильный?',
        options: ['Who like music?', 'Who likes music?', 'Who liking music?'],
        correctAnswer: 'Who likes music?',
        acceptedAnswers: ['Who likes music?'],
        answerFormat: 'choice',
        answerPolicy: 'strict',
        hint: 'Нужна форма likes.',
      },
      footerDynamic: 'Feedback: correct question',
    },
    {
      stepNumber: 7,
      stepType: 'completion',
      bubbles: [
        {
          type: 'positive',
          content: 'Урок завершён. Теперь вы умеете строить простые вопросы с Who и отвечать на них.',
        },
        {
          type: 'info',
          content: 'Используйте шаблон Who + likes + noun? и давайте короткий ясный ответ.',
        },
        {
          type: 'task',
          content: 'Можно закрепить тему на новых ситуациях.',
        },
      ],
      footerDynamic: 'Урок завершён',
      postLesson: {
        dynamicFooterText: 'Выбор за вами! Любое действие закрепит материал',
        staticFooterText: '🏆 +50 XP | 🔥 COMBO x7! | 📈 [████████] 7/7',
        examples: [
          'Who likes music? Anna likes music.',
          'Who likes tea? My brother likes tea.',
          'Who likes music? Nina likes music.',
          'Who likes reading? My friend likes reading.',
          'Who likes chocolate? The kids like chocolate.',
        ],
        interestingFact:
          'В вопросах с Who в английском часто сразу используется форма глагола с -s, потому что вопрос строится вокруг одного неизвестного человека.',
        options: [
          { action: 'repeat_variant', label: 'Повторить с новой ситуацией', icon: '🔁' },
          { action: 'view_examples', label: 'Посмотреть примеры', icon: '📚' },
          { action: 'learn_interesting', label: 'Узнать интересное', icon: '💡' },
          { action: 'independent_practice', label: 'Самостоятельный Практикум', icon: '🎮' },
          { action: 'myeng_training', label: 'Тренировка с MyEng', icon: '🤖' },
        ],
      },
    },
  ],
}
