import type { PracticeExerciseMetadata, PracticeExerciseType } from '@/types/practice'

export const PRACTICE_EXERCISE_REGISTRY: Record<PracticeExerciseType, PracticeExerciseMetadata> = {
  choice: {
    id: 'choice',
    name: 'Quick Choice',
    difficulty: 1,
    skills: ['grammar', 'vocabulary'],
    minLevel: 'A1',
    maxLevel: 'C2',
    xpBase: 5,
    isBossEligible: false,
    tolerance: 'strict',
    locallyAvailable: true,
    modes: ['relaxed', 'balanced', 'challenge'],
    weight: 1.2,
  },
  'voice-shadow': {
    id: 'voice-shadow',
    name: 'Voice Shadow',
    difficulty: 3,
    skills: ['speaking', 'pronunciation'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 8,
    isBossEligible: true,
    tolerance: 'soft',
    locallyAvailable: false,
    modes: ['challenge'],
    weight: 0.6,
  },
  'dropdown-fill': {
    id: 'dropdown-fill',
    name: 'Dropdown Fill',
    difficulty: 2,
    skills: ['grammar'],
    minLevel: 'A1',
    maxLevel: 'C2',
    xpBase: 6,
    isBossEligible: false,
    tolerance: 'strict',
    locallyAvailable: true,
    modes: ['relaxed', 'balanced', 'challenge'],
    weight: 1,
  },
  'listening-select': {
    id: 'listening-select',
    name: 'Listening Select',
    difficulty: 2,
    skills: ['listening'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 6,
    isBossEligible: false,
    tolerance: 'soft',
    locallyAvailable: false,
    modes: ['balanced', 'challenge'],
    weight: 0.6,
  },
  'sentence-surgery': {
    id: 'sentence-surgery',
    name: 'Sentence Surgery',
    difficulty: 3,
    skills: ['grammar', 'vocabulary'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 8,
    isBossEligible: false,
    tolerance: 'strict',
    locallyAvailable: true,
    modes: ['relaxed', 'balanced', 'challenge'],
    weight: 0.9,
  },
  'free-response': {
    id: 'free-response',
    name: 'Free Response',
    difficulty: 4,
    skills: ['speaking', 'grammar'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 10,
    isBossEligible: true,
    tolerance: 'soft',
    locallyAvailable: true,
    modes: ['relaxed', 'balanced', 'challenge'],
    weight: 0.8,
  },
  'word-builder-pro': {
    id: 'word-builder-pro',
    name: 'Word Builder Pro',
    difficulty: 3,
    skills: ['grammar', 'vocabulary'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 8,
    isBossEligible: false,
    tolerance: 'strict',
    locallyAvailable: false,
    modes: ['balanced', 'challenge'],
    weight: 0.6,
  },
  dictation: {
    id: 'dictation',
    name: 'Dictation Lite',
    difficulty: 3,
    skills: ['listening', 'speaking'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 7,
    isBossEligible: false,
    tolerance: 'normalized',
    locallyAvailable: false,
    modes: ['balanced', 'challenge'],
    weight: 0.6,
  },
  'roleplay-mini': {
    id: 'roleplay-mini',
    name: 'Role-Play Mini',
    difficulty: 4,
    skills: ['speaking', 'vocabulary'],
    minLevel: 'B1',
    maxLevel: 'C2',
    xpBase: 10,
    isBossEligible: true,
    tolerance: 'soft',
    locallyAvailable: false,
    modes: ['challenge'],
    weight: 0.5,
  },
  'boss-challenge': {
    id: 'boss-challenge',
    name: 'Boss Challenge',
    difficulty: 5,
    skills: ['grammar', 'listening', 'speaking'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 15,
    isBossEligible: true,
    tolerance: 'normalized',
    locallyAvailable: true,
    modes: ['challenge'],
    weight: 0.4,
  },
  'speed-round': {
    id: 'speed-round',
    name: 'Speed Round',
    difficulty: 2,
    skills: ['vocabulary', 'grammar'],
    minLevel: 'A1',
    maxLevel: 'C2',
    xpBase: 6,
    isBossEligible: false,
    tolerance: 'strict',
    locallyAvailable: true,
    modes: ['balanced', 'challenge'],
    weight: 0.8,
  },
  'context-clue': {
    id: 'context-clue',
    name: 'Context Clue',
    difficulty: 3,
    skills: ['vocabulary', 'grammar'],
    minLevel: 'A2',
    maxLevel: 'C2',
    xpBase: 7,
    isBossEligible: false,
    tolerance: 'normalized',
    locallyAvailable: true,
    modes: ['relaxed', 'balanced', 'challenge'],
    weight: 0.9,
  },
}

export function getPracticeExerciseMetadata(type: PracticeExerciseType): PracticeExerciseMetadata {
  return PRACTICE_EXERCISE_REGISTRY[type]
}
