export const PHRASEBOOK_TOPIC_IDS = [
  'meet',
  'cafe',
  'shop',
  'city',
  'airport',
  'hotel',
  'doctor',
  'home',
  'school',
  'work',
] as const

export type PhrasebookTopicId = (typeof PHRASEBOOK_TOPIC_IDS)[number]

export const DEFAULT_PHRASEBOOK_TOPIC_ID: PhrasebookTopicId = 'meet'

export type PhrasebookLemma = {
  en: string
  ru: string
}

export type PhrasebookTopic = {
  id: PhrasebookTopicId
  title: string
  lemmas: PhrasebookLemma[]
}

export const PHRASEBOOK_TOPICS: PhrasebookTopic[] = [
  {
    id: 'meet',
    title: 'Знакомство',
    lemmas: [
      { en: 'hello', ru: 'привет' },
      { en: 'hi', ru: 'привет' },
      { en: 'name', ru: 'имя' },
      { en: 'my', ru: 'мой' },
      { en: 'your', ru: 'твой' },
      { en: 'nice', ru: 'приятно' },
      { en: 'meet', ru: 'встречать' },
      { en: 'from', ru: 'из' },
      { en: 'friend', ru: 'друг' },
      { en: 'please', ru: 'пожалуйста' },
      { en: 'thanks', ru: 'спасибо' },
      { en: 'sorry', ru: 'извини' },
      { en: 'yes', ru: 'да' },
      { en: 'no', ru: 'нет' },
      { en: 'English', ru: 'английский' },
      { en: 'Russian', ru: 'русский' },
      { en: 'speak', ru: 'говорить' },
      { en: 'a bit', ru: 'немного' },
      { en: 'goodbye', ru: 'до свидания' },
      { en: 'see you', ru: 'увидимся' },
    ],
  },
  {
    id: 'cafe',
    title: 'Кафе',
    lemmas: [
      { en: 'coffee', ru: 'кофе' },
      { en: 'tea', ru: 'чай' },
      { en: 'water', ru: 'вода' },
      { en: 'juice', ru: 'сок' },
      { en: 'menu', ru: 'меню' },
      { en: 'please', ru: 'пожалуйста' },
      { en: 'order', ru: 'заказ' },
      { en: 'sandwich', ru: 'сэндвич' },
      { en: 'pizza', ru: 'пицца' },
      { en: 'soup', ru: 'суп' },
      { en: 'salad', ru: 'салат' },
      { en: 'bread', ru: 'хлеб' },
      { en: 'milk', ru: 'молоко' },
      { en: 'sugar', ru: 'сахар' },
      { en: 'bill', ru: 'счёт' },
      { en: 'card', ru: 'карта' },
      { en: 'cash', ru: 'наличные' },
      { en: 'table', ru: 'стол' },
      { en: 'takeaway', ru: 'с собой' },
      { en: 'delicious', ru: 'вкусно' },
    ],
  },
  {
    id: 'shop',
    title: 'Магазин',
    lemmas: [
      { en: 'shop', ru: 'магазин' },
      { en: 'buy', ru: 'покупать' },
      { en: 'price', ru: 'цена' },
      { en: 'cheap', ru: 'дешёвый' },
      { en: 'expensive', ru: 'дорогой' },
      { en: 'size', ru: 'размер' },
      { en: 'color', ru: 'цвет' },
      { en: 'this', ru: 'этот' },
      { en: 'that', ru: 'тот' },
      { en: 'how much', ru: 'сколько стоит' },
      { en: 'bag', ru: 'сумка' },
      { en: 'clothes', ru: 'одежда' },
      { en: 'shoes', ru: 'обувь' },
      { en: 'shirt', ru: 'рубашка' },
      { en: 'fit', ru: 'подходить' },
      { en: 'try on', ru: 'примерить' },
      { en: 'pay', ru: 'платить' },
      { en: 'receipt', ru: 'чек' },
      { en: 'discount', ru: 'скидка' },
      { en: 'change', ru: 'сдача' },
    ],
  },
  {
    id: 'city',
    title: 'Город и дорога',
    lemmas: [
      { en: 'where', ru: 'где' },
      { en: 'street', ru: 'улица' },
      { en: 'left', ru: 'налево' },
      { en: 'right', ru: 'направо' },
      { en: 'straight', ru: 'прямо' },
      { en: 'near', ru: 'близко' },
      { en: 'far', ru: 'далеко' },
      { en: 'map', ru: 'карта' },
      { en: 'bus', ru: 'автобус' },
      { en: 'taxi', ru: 'такси' },
      { en: 'metro', ru: 'метро' },
      { en: 'stop', ru: 'остановка' },
      { en: 'ticket', ru: 'билет' },
      { en: 'here', ru: 'здесь' },
      { en: 'there', ru: 'там' },
      { en: 'help', ru: 'помощь' },
      { en: 'lost', ru: 'потерялся' },
      { en: 'address', ru: 'адрес' },
      { en: 'walk', ru: 'идти пешком' },
      { en: 'minutes', ru: 'минуты' },
    ],
  },
  {
    id: 'airport',
    title: 'Аэропорт',
    lemmas: [
      { en: 'airport', ru: 'аэропорт' },
      { en: 'flight', ru: 'рейс' },
      { en: 'passport', ru: 'паспорт' },
      { en: 'bag', ru: 'сумка' },
      { en: 'luggage', ru: 'багаж' },
      { en: 'check-in', ru: 'регистрация' },
      { en: 'gate', ru: 'выход на посадку' },
      { en: 'delay', ru: 'задержка' },
      { en: 'boarding', ru: 'посадка' },
      { en: 'ticket', ru: 'билет' },
      { en: 'security', ru: 'безопасность' },
      { en: 'visa', ru: 'виза' },
      { en: 'arrival', ru: 'прилёт' },
      { en: 'departure', ru: 'вылет' },
      { en: 'plane', ru: 'самолёт' },
      { en: 'seat', ru: 'место' },
      { en: 'window', ru: 'окно' },
      { en: 'late', ru: 'поздно' },
      { en: 'early', ru: 'рано' },
      { en: 'transfer', ru: 'пересадка' },
    ],
  },
  {
    id: 'hotel',
    title: 'Отель',
    lemmas: [
      { en: 'hotel', ru: 'отель' },
      { en: 'room', ru: 'номер' },
      { en: 'key', ru: 'ключ' },
      { en: 'reservation', ru: 'бронь' },
      { en: 'night', ru: 'ночь' },
      { en: 'bed', ru: 'кровать' },
      { en: 'bathroom', ru: 'ванная' },
      { en: 'shower', ru: 'душ' },
      { en: 'towel', ru: 'полотенце' },
      { en: 'breakfast', ru: 'завтрак' },
      { en: 'wifi', ru: 'вайфай' },
      { en: 'password', ru: 'пароль' },
      { en: 'floor', ru: 'этаж' },
      { en: 'elevator', ru: 'лифт' },
      { en: 'check-in', ru: 'заселение' },
      { en: 'check-out', ru: 'выселение' },
      { en: 'problem', ru: 'проблема' },
      { en: 'quiet', ru: 'тихо' },
      { en: 'view', ru: 'вид' },
      { en: 'reception', ru: 'ресепшен' },
    ],
  },
  {
    id: 'doctor',
    title: 'Врач',
    lemmas: [
      { en: 'doctor', ru: 'врач' },
      { en: 'ill', ru: 'болен' },
      { en: 'pain', ru: 'боль' },
      { en: 'head', ru: 'голова' },
      { en: 'throat', ru: 'горло' },
      { en: 'cough', ru: 'кашель' },
      { en: 'temperature', ru: 'температура' },
      { en: 'medicine', ru: 'лекарство' },
      { en: 'allergy', ru: 'аллергия' },
      { en: 'hospital', ru: 'больница' },
      { en: 'appointment', ru: 'приём' },
      { en: 'hurt', ru: 'больно' },
      { en: 'tired', ru: 'устал' },
      { en: 'better', ru: 'лучше' },
      { en: 'worse', ru: 'хуже' },
      { en: 'rest', ru: 'отдых' },
      { en: 'water', ru: 'вода' },
      { en: 'help', ru: 'помощь' },
      { en: 'emergency', ru: 'срочно' },
      { en: 'pharmacy', ru: 'аптека' },
    ],
  },
  {
    id: 'home',
    title: 'Дом и семья',
    lemmas: [
      { en: 'home', ru: 'дом' },
      { en: 'house', ru: 'дом' },
      { en: 'family', ru: 'семья' },
      { en: 'mum', ru: 'мама' },
      { en: 'dad', ru: 'папа' },
      { en: 'brother', ru: 'брат' },
      { en: 'sister', ru: 'сестра' },
      { en: 'child', ru: 'ребёнок' },
      { en: 'room', ru: 'комната' },
      { en: 'kitchen', ru: 'кухня' },
      { en: 'food', ru: 'еда' },
      { en: 'sleep', ru: 'спать' },
      { en: 'morning', ru: 'утро' },
      { en: 'evening', ru: 'вечер' },
      { en: 'today', ru: 'сегодня' },
      { en: 'tomorrow', ru: 'завтра' },
      { en: 'together', ru: 'вместе' },
      { en: 'love', ru: 'любить' },
      { en: 'pet', ru: 'питомец' },
      { en: 'live', ru: 'жить' },
    ],
  },
  {
    id: 'school',
    title: 'Учёба',
    lemmas: [
      { en: 'school', ru: 'школа' },
      { en: 'class', ru: 'класс' },
      { en: 'teacher', ru: 'учитель' },
      { en: 'student', ru: 'ученик' },
      { en: 'lesson', ru: 'урок' },
      { en: 'homework', ru: 'домашка' },
      { en: 'test', ru: 'тест' },
      { en: 'book', ru: 'книга' },
      { en: 'pen', ru: 'ручка' },
      { en: 'desk', ru: 'парта' },
      { en: 'question', ru: 'вопрос' },
      { en: 'answer', ru: 'ответ' },
      { en: 'understand', ru: 'понимать' },
      { en: 'repeat', ru: 'повторить' },
      { en: 'break', ru: 'перемена' },
      { en: 'timetable', ru: 'расписание' },
      { en: 'subject', ru: 'предмет' },
      { en: 'English', ru: 'английский' },
      { en: 'late', ru: 'опоздал' },
      { en: 'exam', ru: 'экзамен' },
    ],
  },
  {
    id: 'work',
    title: 'Работа и договорённости',
    lemmas: [
      { en: 'work', ru: 'работа' },
      { en: 'job', ru: 'работа' },
      { en: 'office', ru: 'офис' },
      { en: 'meeting', ru: 'встреча' },
      { en: 'email', ru: 'почта' },
      { en: 'call', ru: 'звонок' },
      { en: 'message', ru: 'сообщение' },
      { en: 'tomorrow', ru: 'завтра' },
      { en: 'time', ru: 'время' },
      { en: 'busy', ru: 'занят' },
      { en: 'wait', ru: 'ждать' },
      { en: 'later', ru: 'позже' },
      { en: 'send', ru: 'отправить' },
      { en: 'need', ru: 'нужно' },
      { en: 'help', ru: 'помощь' },
      { en: 'deadline', ru: 'срок' },
      { en: 'colleague', ru: 'коллега' },
      { en: 'boss', ru: 'начальник' },
      { en: 'online', ru: 'онлайн' },
      { en: 'weekend', ru: 'выходные' },
    ],
  },
]

const TOPIC_BY_ID = new Map(PHRASEBOOK_TOPICS.map((topic) => [topic.id, topic]))

export function isPhrasebookTopicId(value: string): value is PhrasebookTopicId {
  return (PHRASEBOOK_TOPIC_IDS as readonly string[]).includes(value)
}

export function getPhrasebookTopic(id: PhrasebookTopicId): PhrasebookTopic {
  return TOPIC_BY_ID.get(id) ?? PHRASEBOOK_TOPICS[0]!
}
