import { REFERENCE_READING_CARD_LABELS } from '@/lib/uiCopy/lessonReadingCards'

export const REFERENCE_COPY = {
  menuRootLabel: 'Справочник',
  hubTitle: 'Справочник',
  byLevelLabel: 'По уровню',
  byTopicLabel: 'По теме',
  lessonsSectionTitle: 'Уроки',
  tagLevelsTitle: 'Уровень по теме',
  tagLessonsTitle: 'Тема по тегу',
  topicCta: 'Справочник',
  topicBrowsePlaceholder: 'Например: вопросы или present',
  topicBrowseEmpty: 'Ничего не нашлось. Попробуй другое слово.',
  searchPlaceholder: 'Например: I am или it’s time',
  searchSubmit: 'Найти',
  searchEmpty: 'Пока нет готовой шпаргалки по этому запросу.',
  searchMissHint: 'Попробуй другое слово или открой тему по уровню.',
  searchMissAskTutor: 'Готовой шпаргалки нет. Можно спросить репетитора.',
  searchAskTutor: 'Спросить репетитора',
  searchGenerateHint: 'Собираю шпаргалку по этому запросу…',
  searchNeedQuery: 'Введи слово или фразу для поиска.',
  searchChooseHint: 'Уточни, что открыть:',
  searchHitsLabel: 'Найдено',
  cardHook: REFERENCE_READING_CARD_LABELS.essence,
  cardRule: REFERENCE_READING_CARD_LABELS.rule,
  cardFormula: REFERENCE_READING_CARD_LABELS.templates,
  cardExamples: REFERENCE_READING_CARD_LABELS.examples,
  cardContrast: REFERENCE_READING_CARD_LABELS.contrast,
  cardTraps: REFERENCE_READING_CARD_LABELS.mistakes,
  cardSelfCheck: REFERENCE_READING_CARD_LABELS.selfCheck,
  back: '← Назад',
  startLesson: 'Пройти урок',
  startPractice: 'Практика',
  myPlanSecondary: 'Справочник',
} as const
