export const REFERENCE_COPY = {
  menuRootLabel: 'Справочник',
  hubTitle: 'Справочник',
  byLevelLabel: 'По уровню',
  byTopicLabel: 'По теме',
  tagLevelsTitle: 'Уровень по теме',
  tagLessonsTitle: 'Тема по тегу',
  topicCta: 'Шпаргалка',
  searchPlaceholder: 'Например: I am или it’s time',
  searchEmpty: 'Нет шпаргалки по запросу. Попробуй Теорию или Репетитор.',
  searchHitsLabel: 'Найдено',
  cardHook: 'Крючок',
  cardRule: 'Правило',
  cardFormula: 'Формула',
  cardTraps: 'Ловушки',
  cardExamples: 'Примеры',
  back: '← Назад',
  startLesson: 'Начать урок',
  startPractice: 'Практика',
  myPlanSecondary: 'Шпаргалка',
} as const
